dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.7"
services:
  - mysql
before_install:
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('trading_pass') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo mysql_upgrade -u root -ptrading_pass
  - sudo service mysql restart
install:
  - pip install -r requirements_test.txt
# command to run tests
script:
  - py.test --pep8
  - pytest --cov=.
after_success:
  - coveralls
