dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.7"
install:
  - pip install -r requirements_test.txt
# command to run tests
script:
  - py.test --pep8
  - pytest --cov=request_handler tests/request_handler
after_success:
  - coveralls
