dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.7"
install:
  - pip install -r request_handler/requirements/production.txt
  - pip install -r requirements_test.txt
# command to run tests
script:
  - py.test --pep8
after_success:
  - cat ./coverage/lconv.info | ./node_modules/codecov.io/bin/codecov.io.js
  - cat ./coverage/lconv.info | ./node_modules/coveralls/bin/coveralls.js
