#!/bin/bash

echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker build -t $DOCKER_USERNAME/request_handler:latest ./request_handler
docker push $DOCKER_USERNAME/request_handler:latest
