#!/bin/bash

echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker build -t asasgard/request_handler:latest ./request_handler
docker push asasgard/request_handler:latest
